# ==============================================================================
# Kwin System Widget - Configuration File
# ==============================================================================
#
# Format: key=value
# Comment # nebo ;

# ------------------------------------------------------------------------------
# WAYLAND SURFACE WINDOW - window size for draw
# ------------------------------------------------------------------------------
[surface_window]
width=520
height=920

# ------------------------------------------------------------------------------
# MAIN WINDOW FOR WIDGETS WITH FRAME AND SHADOW
# ------------------------------------------------------------------------------
# dashboard
[main_window]
# Position and size
x=10.0
y=5.0
width=500.0
height=900.0

# Corner
corner_radius=15.0

# Shadow
shadow_offset=0.5
shadow_blur=0.8
shadow_alpha=0.2

# Frame - stroke
stroke_width=2.0

# Backgound color (RGBA: 0.0-1.0)
bg_r=0.0
bg_g=0.0
bg_b=0.0
bg_a=0.5

# Frame color (RGBA)
stroke_r=0.2
stroke_g=0.6
stroke_b=1.0
stroke_a=0.0

# Shadow (RGBA)
shadow_r=0.0
shadow_g=0.0
shadow_b=0.0
shadow_a=0.5

# Backgound shadow (fill)
shadow_fill_offset=0.5
shadow_fill_blur=0.8
shadow_fill_alpha=0.2
shadow_fill_r=0.0
shadow_fill_g=0.0
shadow_fill_b=0.0
shadow_fill_a=1.0

# Frame shadow (stroke)
shadow_stroke_offset=0.5
shadow_stroke_blur=0.8
shadow_stroke_alpha=0.5
shadow_stroke_r=0.0
shadow_stroke_g=0.6
shadow_stroke_b=0.8
shadow_stroke_a=1.0

# ------------------------------------------------------------------------------
# WIDGETS
# ------------------------------------------------------------------------------
# Formát: enabled, x, y, width, height
# enabled = true/false (show/hide widget)

[widget.sysinfo]
enabled=true
x=20
y=20
width=480
height=100

[widget.cpu]
enabled=true
x=20
y=140
width=480
height=100

[widget.gpu]
enabled=true
x=20
y=260
width=480
height=100

[widget.ram]
enabled=true
x=20
y=400
width=480
height=30

[widget.storage]
enabled=true
x=20
y=460
width=480
height=220

[widget.network]
enabled=true
x=20
y=690
width=480
height=160

[widget.clock]
enabled=true
x=230
y=795
width=30
height=30

# ------------------------------------------------------------------------------
# NETWORK -
# ------------------------------------------------------------------------------
[network]
# auto-detection or manual use interface
auto_detect=false

# Interface name (if auto_detect=false)
# ip link show
interface=wlp13s0f3u3u2

# Examples:
# interface=wlan0          # WiFi (laptop)
# interface=enp9s0         # Ethernet (desktop)
# interface=wlp80s0        # WiFi (jiný laptop)

